name: ml

channels:
  - pytorch-nightly
  - conda-forge
  - defaults

dependencies:
  - python >=3.9
  - matplotlib
  - numpy >=1.20
  - pytorch >=1.11.0
  - librosa >=0.9
  - ffmpeg >=5.0
  - autopep8
